# rails_app01/docker-compose.yml
services:
  web:
    build: .
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    volumes:
      - '.:/rails_app01'
    ports:
      - '3001:3000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_app01_development
    ports:
      - '3306:3306'
