default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: rails_app02_development

test:
  <<: *default
  database: rails_app02_test

production:
  <<: *default
  database: rails_app01_production
  username: rails_app02
  password: <%= ENV["RAILS_APP01_DATABASE_PASSWORD"] %>
